nelmio_api_doc:
    documentation:
        info:
            title: Makkelijke Markt API
            description: API voor de Makkelijke Markt Android app
            version: 1.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^/1\.1\.0 # Accepts routes under /1.1.0
