version: "3.2"

services:
  database:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: makkelijkemarkt
      POSTGRES_PASSWORD: insecure

  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - database
    command: ["/usr/bin/wait-for-it.sh", "database:5432", "--" , "/app/docker-entrypoint.sh"]
    links:
    - database:database
    environment:
      MM_API__DATABASE__HOST: "database"
      MM_API__DATABASE__PORT: "5432"
      MM_API__DATABASE__NAME: "makkelijkemarkt"
      MM_API__DATABASE__USER: "makkelijkemarkt"
      MM_API__DATABASE__PASSWORD: "insecure"
      MM_API__MAILER__TRANSPORT: "smtp"
      MM_API__MAILER__HOST: "localhost"
      MM_API__MAILER__USER: ""
      MM_API__MAILER__PASSWORD: ""
      MM_API__MAILER__PORT: "25"
      MM_API__MAILER__ENCRYPTION: "ssl" # null, ssl, tls
      MM_API__SECRET: "insecure" # random
      MM_API__APP_KEY: "insecure"
